export const parcelTypes = [
  { label: 'Small Box', value: 'smallBox' },
  { label: 'Medium Box', value: 'mediumBox' },
  { label: 'Large Box', value: 'largeBox' },
  { label: 'Envelope', value: 'envelope' },
  { label: 'Pouch', value: 'pouch' },
  { label: 'Tube', value: 'tube' },
  { label: 'Crate', value: 'crate' },
  { label: 'Pallet', value: 'pallet' },
  { label: 'Fragile Goods', value: 'fragileGoods' },
  { label: 'Perishable Goods', value: 'perishableGoods' },
  { label: 'Hazardous Materials', value: 'hazardousMaterials' },
  { label: 'Oversized', value: 'oversized' },
  { label: 'Irregular Shape', value: 'irregularShape' },
  { label: 'Document', value: 'document' },
];
